# Основные структуры данных в R и установка и подключение пакетов
## Описание
В этом уроке мы разберём основные структуры данных в языке программирования R и сравним их с Excel.

Структуры данных рассмотренные в уроке:
1. Векторы
2. Таблицы (дата фреймы)
3. Списки

## Видео
<iframe width="560" height="315" src="https://www.youtube.com/embed/GwqoGHa8wjQ?enablejsapi=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Материалы
Все материалы к данному уроку можно найти по [ссылке](https://github.com/selesnow/r4excel_users/tree/master/lesson_2).

## Код
```{r eval=FALSE}
# переменная
x <- 1

# вектор
y <- 1:10
typeof(y)
strings <- c("string", "vector")
typeof(strings)
vec <- c(3, "string")
typeof(vec)

# обраение к элементу вектора
strings[1]
strings[2]
y[3:6]
y[c(2, 5, 9)]

# таблица, data frame
df1 <- data.frame(a = 1:3,
                  b = c("a", "b", "c"))

# обратиться к определённому столбцу таблицы
df1$a
df1['a']

# списки
typeof(df1)
class(df1)
list1 <- list(y, strings, vec, df1)
list2 <- list(node1 = c(1, 5, 8),
              node2 = list("y", 3, "p"))

# структура объекта
str(df1)
str(list2)
str(vec)
```

## Тест
<iframe id="otpwgt-wt101505" src="https://onlinetestpad.com/hr5y6i3gyunfu" frameborder="0" style="width:100%;" onload="var f = document.getElementById('otpwgt-wt101505'); var h = 0; var listener = function (event) { if (event.origin.indexOf('onlinetestpad') == -1) { return; }; h = parseInt(event.data); if (!isNaN(h)) f.style.height = h + 'px'; }; function addEvent(elem, evnt, func) { if (elem.addEventListener) { elem.addEventListener(evnt, func, false); } else if (elem.attachEvent) { elem.attachEvent('on' + evnt, func); } else { elem['on' + evnt] = func; } }; addEvent(window, 'message', listener);" scrolling="no" ></iframe>
