# Чтение данных из TSV, CSV, Excel файлов и Google Таблиц
## Описание
В этом уроке мы разберёмся как загружать данные для дальнейшей обработки на языке R.

Мы загрузим данные из csv, tsv, Excel файлов и Google Таблиц.

Разберёмся с такими R пакетами как: `vroom`, `readxl`, `googlesheets4`

## Видео
<iframe width="560" height="315" src="https://www.youtube.com/embed/vVFFtgcBp-w?enablejsapi=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Материалы
Все материалы к данному уроку можно найти по [ссылке](https://github.com/selesnow/r4excel_users/tree/master/lesson_3).

+ [ga_december.csv](https://github.com/selesnow/r4excel_users/raw/52ce5604b653ee0490c299907b7184992d5a5107/lesson_3/ga_december.csv)
+ [ga_nowember.csv](https://github.com/selesnow/r4excel_users/raw/52ce5604b653ee0490c299907b7184992d5a5107/lesson_3/ga_nowember.csv)
+ [ga_examples.xlsx](https://github.com/selesnow/r4excel_users/raw/52ce5604b653ee0490c299907b7184992d5a5107/lesson_3/ga_examples.xlsx)

## Код
```{r eval=FALSE}
# Загрузка данных в R
# Установка пакетов
install.packages("vroom")
install.packages("readxl")
install.packages("devtools")
devtools::install_github("tidyverse/googlesheets4")

# ###########################################
# подключение пакетов
library("vroom")


# ###########################################
# Чтение CSV, TSV и прочих текстовых файлов

## чтение локальных файлов
ga_data <- vroom(file = "D:/materials/lesson_3/ga_nowember.csv", delim = "/t")
## чтение файлов опубликованных в интернете
ga_data_i <- vroom("https://raw.githubusercontent.com/selesnow/publications/master/data_example/russian_text_in_r/ga_nowember.csv")

## чтение нескольких файлов в одну таблицу
files   <- dir(pattern = "\\.csv$")
ga_full <- vroom(files) 


# ###########################################
# Чтение Excel файлов
library(readxl)

## получить список листов из Excel файла
excel_sheets("D:/materials/lesson_3/ga_examples.xlsx")

## считать данные с листа
xl_dec <- read_excel("D:/materials/lesson_3/ga_examples.xlsx", sheet = "dec")

# ###########################################
# Чтение Google Таблиц
library(googlesheets4)

## Авторихация
sheets_auth(email = "selesnow@gmail.com")
sheets_find()
## Подклбчение к доксу
ss_id <- as_sheets_id("1xu_beKZVpJJTHTvAab_vN3ZiMB03BytKArGjJUO8cck")

## открыть докс в браузере
sheets_browse(ss)

## посмотреть список листов
sheets_sheet_names(ss)

## получить данные из листа
gs_ga_data <- sheets_read(ss = ss_id, 
                          sheet = "dec")

## получить данные из диапазона на листе
gs_ga_data <- sheets_read(ss = ss, 
                          sheet = "dec", 
                          range = "A1:C10")
```

## Тест
<iframe id="otpwgt-wt101545" src="https://onlinetestpad.com/hrjuikkvlaif2" frameborder="0" style="width:100%;" onload="var f = document.getElementById('otpwgt-wt101545'); var h = 0; var listener = function (event) { if (event.origin.indexOf('onlinetestpad') == -1) { return; }; h = parseInt(event.data); if (!isNaN(h)) f.style.height = h + 'px'; }; function addEvent(elem, evnt, func) { if (elem.addEventListener) { elem.addEventListener(evnt, func, false); } else if (elem.attachEvent) { elem.attachEvent('on' + evnt, func); } else { elem['on' + evnt] = func; } }; addEvent(window, 'message', listener);" scrolling="no" ></iframe>
